parameters:
    bitbag_es_shop_brand_taxons_property: brand_taxons

fos_elastica:
    indexes:
        bitbag_brand_taxons:
            index_name: "%bitbag_es_index_prefix%bitbag_brand_taxons_%kernel.environment%"
            properties:
                brand_code:
                    property_path: code
            persistence:
                driver: orm
                model: "%loevgaard_sylius_brand.model.brand.class%"
                listener:
                    defer: false
                    logger: true
                elastica_to_model_transformer:
                    ignore_missing: true
